version: "3.8"

services:
  application:
    image: liudmila145/application:lasttag
    ports:
      - "80:80"
    depends_on:
      - wordpress-mysql
    networks:
      test-network:

  wordpress-mysql:
    image: mysql:8.0
    volumes:
      - wordpress-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      test-network:

  wordpress-monitoring:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      test-network:

volumes:
  wordpress-mysql:

networks:
  test-network: